export const placeholderRecipes = {
  results: [
    {
      vegetarian: true,
      vegan: false,
      glutenFree: false,
      dairyFree: false,
      veryHealthy: false,
      cheap: false,
      veryPopular: false,
      sustainable: false,
      lowFodmap: false,
      weightWatcherSmartPoints: 3,
      gaps: "no",
      preparationMinutes: -1,
      cookingMinutes: -1,
      aggregateLikes: 19,
      healthScore: 1,
      creditsText: "Foodista.com – The Cooking Encyclopedia Everyone Can Edit",
      license: "CC BY 3.0",
      sourceName: "Foodista",
      pricePerServing: 43.26,
      extendedIngredients: [Array],
      id: 636962,
      title: "Caprese Quick Bread",
      readyInMinutes: 45,
      servings: 12,
      sourceUrl: "https://www.foodista.com/recipe/W5MF623S/caprese-quick-bread",
      image: "https://spoonacular.com/recipeImages/636962-312x231.jpg",
      imageType: "jpg",
      summary:
        'Forget going out to eat or ordering takeout every time you crave Mediterranean food. Try making Caprese Quick Bread at home. Watching your figure? This lacto ovo vegetarian recipe has <b>118 calories</b>, <b>5g of protein</b>, and <b>5g of fat</b> per serving. This recipe serves 12 and costs 43 cents per serving. 19 people have made this recipe and would make it again. A couple people really liked this breakfast. From preparation to the plate, this recipe takes about <b>45 minutes</b>. It is brought to you by Foodista. A mixture of flour, olive oil, weight lite mozzarella cheese, and a handful of other ingredients are all it takes to make this recipe so tasty. Taking all factors into account, this recipe <b>earns a spoonacular score of 26%</b>, which is rather bad. Try <a href="https://spoonacular.com/recipes/caprese-quick-bread-1411633">Caprese Quick Bread</a>, <a href="https://spoonacular.com/recipes/quick-caprese-salad-551296">Quick Caprese Salad</a>, and <a href="https://spoonacular.com/recipes/quick-and-easy-caprese-salad-657537">Quick and Easy Caprese Salad</a> for similar recipes.',
      cuisines: [Array],
      dishTypes: [Array],
      diets: [Array],
      occasions: [],
      analyzedInstructions: [Array],
      spoonacularSourceUrl:
        "https://spoonacular.com/caprese-quick-bread-636962",
      usedIngredientCount: 4,
      missedIngredientCount: 3,
      likes: 0,
      missedIngredients: [Array],
      usedIngredients: [Array],
      unusedIngredients: [Array],
    },
    {
      vegetarian: false,
      vegan: false,
      glutenFree: false,
      dairyFree: false,
      veryHealthy: false,
      cheap: false,
      veryPopular: false,
      sustainable: false,
      lowFodmap: false,
      weightWatcherSmartPoints: 17,
      gaps: "no",
      preparationMinutes: -1,
      cookingMinutes: -1,
      aggregateLikes: 1,
      healthScore: 10,
      creditsText: "Foodista.com – The Cooking Encyclopedia Everyone Can Edit",
      license: "CC BY 3.0",
      sourceName: "Foodista",
      pricePerServing: 221.77,
      extendedIngredients: [Array],
      id: 663745,
      title: "Totally Fresh Tomato Lasagna",
      readyInMinutes: 75,
      servings: 4,
      sourceUrl:
        "http://www.foodista.com/recipe/RGPCXQ4J/totally-fresh-tomato-lasagna",
      image: "https://spoonacular.com/recipeImages/663745-312x231.jpg",
      imageType: "jpg",
      summary:
        'Forget going out to eat or ordering takeout every time you crave Mediterranean food. Try making Totally Fresh Tomato Lasagnan at home. This recipe makes 4 servings with <b>541 calories</b>, <b>25g of protein</b>, and <b>31g of fat</b> each. For <b>$2.22 per serving</b>, this recipe <b>covers 21%</b> of your daily requirements of vitamins and minerals. A mixture of no-boil lasagna noodles, water, olive oil, and a handful of other ingredients are all it takes to make this recipe so delicious. This recipe is liked by 1 foodies and cooks. From preparation to the plate, this recipe takes roughly <b>1 hour and 15 minutes</b>. It is brought to you by Foodista. It works well as a rather inexpensive main course. All things considered, we decided this recipe <b>deserves a spoonacular score of 55%</b>. This score is solid. Similar recipes are <a href="https://spoonacular.com/recipes/fresh-tomato-lasagna-227702">Fresh-Tomato Lasagna</a>, <a href="https://spoonacular.com/recipes/garden-fresh-lasagna-160936">Garden-Fresh Lasagna</a>, and <a href="https://spoonacular.com/recipes/fresh-vegetable-lasagna-197475">Fresh Vegetable Lasagna</a>.',
      cuisines: [Array],
      dishTypes: [Array],
      diets: [],
      occasions: [],
      analyzedInstructions: [Array],
      spoonacularSourceUrl:
        "https://spoonacular.com/totally-fresh-tomato-lasagna-663745",
      usedIngredientCount: 4,
      missedIngredientCount: 4,
      likes: 0,
      missedIngredients: [Array],
      usedIngredients: [Array],
      unusedIngredients: [Array],
    },
    {
      vegetarian: false,
      vegan: false,
      glutenFree: false,
      dairyFree: false,
      veryHealthy: false,
      cheap: false,
      veryPopular: false,
      sustainable: false,
      lowFodmap: false,
      weightWatcherSmartPoints: 23,
      gaps: "no",
      preparationMinutes: -1,
      cookingMinutes: -1,
      aggregateLikes: 1,
      healthScore: 12,
      creditsText: "Foodista.com – The Cooking Encyclopedia Everyone Can Edit",
      license: "CC BY 3.0",
      sourceName: "Foodista",
      pricePerServing: 382.34,
      extendedIngredients: [Array],
      id: 640909,
      title: "Croque-Madame with Asparagus",
      readyInMinutes: 45,
      servings: 4,
      sourceUrl:
        "https://www.foodista.com/recipe/QT3QTDD4/croque-madame-with-asparagus",
      image: "https://spoonacular.com/recipeImages/640909-312x231.jpg",
      imageType: "jpg",
      summary:
        'Croque-Madame with Asparagus might be a good recipe to expand your main course recipe box. One serving contains <b>690 calories</b>, <b>37g of protein</b>, and <b>46g of fat</b>. For <b>$3.82 per serving</b>, this recipe <b>covers 24%</b> of your daily requirements of vitamins and minerals. This recipe serves 4. This recipe is liked by 1 foodies and cooks. From preparation to the plate, this recipe takes around <b>45 minutes</b>. This recipe from Foodista requires eggs, olive oil, salt & pepper, and flour. Overall, this recipe earns a <b>solid spoonacular score of 47%</b>. If you like this recipe, take a look at these similar recipes: <a href="https://spoonacular.com/recipes/croque-madame-198031">Croque-Madame</a>, <a href="https://spoonacular.com/recipes/croque-madame-626759">Croque Madame</a>, and <a href="https://spoonacular.com/recipes/croque-madame-293548">Croque Madame</a>.',
      cuisines: [],
      dishTypes: [Array],
      diets: [],
      occasions: [],
      analyzedInstructions: [Array],
      spoonacularSourceUrl:
        "https://spoonacular.com/croque-madame-with-asparagus-640909",
      usedIngredientCount: 4,
      missedIngredientCount: 6,
      likes: 0,
      missedIngredients: [Array],
      usedIngredients: [Array],
      unusedIngredients: [Array],
    },
    {
      vegetarian: false,
      vegan: false,
      glutenFree: false,
      dairyFree: false,
      veryHealthy: false,
      cheap: false,
      veryPopular: false,
      sustainable: false,
      lowFodmap: false,
      weightWatcherSmartPoints: 15,
      gaps: "no",
      preparationMinutes: -1,
      cookingMinutes: -1,
      aggregateLikes: 3,
      healthScore: 1,
      creditsText: "Foodista.com – The Cooking Encyclopedia Everyone Can Edit",
      license: "CC BY 3.0",
      sourceName: "Foodista",
      pricePerServing: 44.91,
      extendedIngredients: [Array],
      id: 638879,
      title: "Chocolate Caramel Cupcakes",
      readyInMinutes: 45,
      servings: 20,
      sourceUrl:
        "https://www.foodista.com/recipe/RNDJXKLN/chocolate-caramel-cupcakes",
      image: "https://spoonacular.com/recipeImages/638879-312x231.jpg",
      imageType: "jpg",
      summary:
        'If you want to add more <b>American</b> recipes to your recipe box, Chocolate Caramel Cupcakes might be a recipe you should try. One portion of this dish contains approximately <b>4g of protein</b>, <b>13g of fat</b>, and a total of <b>324 calories</b>. For <b>45 cents per serving</b>, this recipe <b>covers 7%</b> of your daily requirements of vitamins and minerals. This recipe serves 20. Head to the store and pick up eggs, brown suger, baking soda, and a few other things to make it today. From preparation to the plate, this recipe takes around <b>45 minutes</b>. This recipe is liked by 3 foodies and cooks. Not a lot of people really liked this dessert. It is brought to you by Foodista. Taking all factors into account, this recipe <b>earns a spoonacular score of 23%</b>, which is rather bad. Similar recipes are <a href="https://spoonacular.com/recipes/white-chocolate-caramel-latte-cupcakes-for-national-chocolate-caramel-day-260548">White Chocolate Caramel Latte Cupcakes for National Chocolate Caramel Day</a>, <a href="https://spoonacular.com/recipes/karamel-sutra-cupcakes-chocolate-and-caramel-swirl-cupcakes-631382">Karamel Sutra Cupcakes (Chocolate and Caramel Swirl Cupcakes)</a>, and <a href="https://spoonacular.com/recipes/karamel-sutra-cupcakes-chocolate-and-caramel-swirl-cupcakes-1199205">Karamel Sutra Cupcakes (Chocolate and Caramel Swirl Cupcakes)</a>.',
      cuisines: [Array],
      dishTypes: [Array],
      diets: [],
      occasions: [],
      analyzedInstructions: [Array],
      spoonacularSourceUrl:
        "https://spoonacular.com/chocolate-caramel-cupcakes-638879",
      usedIngredientCount: 5,
      missedIngredientCount: 4,
      likes: 0,
      missedIngredients: [Array],
      usedIngredients: [Array],
      unusedIngredients: [Array],
    },
    {
      vegetarian: false,
      vegan: false,
      glutenFree: false,
      dairyFree: false,
      veryHealthy: false,
      cheap: false,
      veryPopular: false,
      sustainable: false,
      lowFodmap: false,
      weightWatcherSmartPoints: 31,
      gaps: "no",
      preparationMinutes: 0,
      cookingMinutes: 20,
      aggregateLikes: 1,
      healthScore: 28,
      creditsText: "Foodista.com – The Cooking Encyclopedia Everyone Can Edit",
      license: "CC BY 3.0",
      sourceName: "Foodista",
      pricePerServing: 696.81,
      extendedIngredients: [Array],
      id: 640779,
      title: "Crespelle with Mozzarella, Parma Ham and Tomato Sauce",
      readyInMinutes: 65,
      servings: 4,
      sourceUrl:
        "http://www.foodista.com/recipe/LKKCKS8T/crespelle-with-mozzarella-parma-ham-and-tomato-sauce",
      image: "https://spoonacular.com/recipeImages/640779-312x231.jpg",
      imageType: "jpg",
      summary:
        'Crespelle with Mozzarella, Parma Ham and Tomato Sauce might be just the main course you are searching for. This recipe makes 4 servings with <b>977 calories</b>, <b>53g of protein</b>, and <b>58g of fat</b> each. For <b>$6.97 per serving</b>, this recipe <b>covers 39%</b> of your daily requirements of vitamins and minerals. This recipe from Foodista has 1 fans. A mixture of garlic cloves, 5 oz. of butter to cook the pancakes, shallots, and a handful of other ingredients are all it takes to make this recipe so delicious. From preparation to the plate, this recipe takes roughly <b>1 hour and 5 minutes</b>. Taking all factors into account, this recipe <b>earns a spoonacular score of 66%</b>, which is solid. Try <a href="https://spoonacular.com/recipes/parma-ham-mozzarella-risotto-1092024">Parma ham mozzarella risotto</a>, <a href="https://spoonacular.com/recipes/parma-ham-peach-plates-219116">Parma ham & peach plates</a>, and <a href="https://spoonacular.com/recipes/baked-scallops-with-parma-ham-633786">Baked Scallops With Parma Ham</a> for similar recipes.',
      cuisines: [],
      dishTypes: [Array],
      diets: [],
      occasions: [],
      analyzedInstructions: [Array],
      spoonacularSourceUrl:
        "https://spoonacular.com/crespelle-with-mozzarella-parma-ham-and-tomato-sauce-640779",
      usedIngredientCount: 4,
      missedIngredientCount: 6,
      likes: 0,
      missedIngredients: [Array],
      usedIngredients: [Array],
      unusedIngredients: [Array],
    },
    {
      vegetarian: true,
      vegan: false,
      glutenFree: false,
      dairyFree: false,
      veryHealthy: false,
      cheap: false,
      veryPopular: false,
      sustainable: false,
      lowFodmap: false,
      weightWatcherSmartPoints: 1,
      gaps: "no",
      preparationMinutes: -1,
      cookingMinutes: -1,
      aggregateLikes: 1,
      healthScore: 7,
      creditsText: "Foodista.com – The Cooking Encyclopedia Everyone Can Edit",
      license: "CC BY 3.0",
      sourceName: "Foodista",
      pricePerServing: 56.85,
      extendedIngredients: [Array],
      id: 648345,
      title: "Jalapeño Corn Cakes With Avocado Salsa",
      readyInMinutes: 45,
      servings: 60,
      sourceUrl:
        "https://www.foodista.com/recipe/ZMNTRKRQ/jalapeno-corn-cakes-with-avocado-salsa",
      image: "https://spoonacular.com/recipeImages/648345-312x231.jpg",
      imageType: "jpg",
      summary:
        'Forget going out to eat or ordering takeout every time you crave Mexican food. Try making Jalapeño Corn Cakes With Avocado Salsan at home. This recipe serves 60 and costs 57 cents per serving. Watching your figure? This lacto ovo vegetarian recipe has <b>77 calories</b>, <b>2g of protein</b>, and <b>3g of fat</b> per serving. This recipe is liked by 1 foodies and cooks. Head to the store and pick up bell pepper, salt and pepper, butter, and a few other things to make it today. It is brought to you by Foodista. It works well as a very reasonably priced side dish. From preparation to the plate, this recipe takes roughly <b>45 minutes</b>. All things considered, we decided this recipe <b>deserves a spoonacular score of 13%</b>. This score is rather bad. If you like this recipe, take a look at these similar recipes: <a href="https://spoonacular.com/recipes/jalapeno-corn-cakes-with-avocado-salsa-551639">Jalapeno Corn Cakes with Avocado Salsa</a>, <a href="https://spoonacular.com/recipes/jalapeno-jack-polenta-cakes-with-cilantro-corn-salsa-133405">Jalapeno-Jack Polenta Cakes With Cilantro Corn Salsa</a>, and <a href="https://spoonacular.com/recipes/cheesy-corn-cakes-with-spicy-avocado-salsa-513173">Cheesy Corn Cakes with Spicy Avocado Salsa</a>.',
      cuisines: [Array],
      dishTypes: [Array],
      diets: [Array],
      occasions: [],
      analyzedInstructions: [Array],
      spoonacularSourceUrl:
        "https://spoonacular.com/jalapeo-corn-cakes-with-avocado-salsa-648345",
      usedIngredientCount: 4,
      missedIngredientCount: 10,
      likes: 0,
      missedIngredients: [Array],
      usedIngredients: [Array],
      unusedIngredients: [Array],
    },
    {
      vegetarian: false,
      vegan: false,
      glutenFree: false,
      dairyFree: false,
      veryHealthy: false,
      cheap: false,
      veryPopular: false,
      sustainable: false,
      lowFodmap: false,
      weightWatcherSmartPoints: 21,
      gaps: "no",
      preparationMinutes: -1,
      cookingMinutes: -1,
      aggregateLikes: 15,
      healthScore: 13,
      creditsText: "Foodista.com – The Cooking Encyclopedia Everyone Can Edit",
      license: "CC BY 3.0",
      sourceName: "Foodista",
      pricePerServing: 156.93,
      extendedIngredients: [Array],
      id: 638568,
      title: "Chili Pie with Green Chile and Cheddar Cornbread Crust",
      readyInMinutes: 60,
      servings: 8,
      sourceUrl:
        "http://www.foodista.com/recipe/R526VXXY/chili-pie-w-green-chile-cheddar-cornbread-crust",
      image: "https://spoonacular.com/recipeImages/638568-312x231.jpg",
      imageType: "jpg",
      summary:
        'If you want to add more <b>Southern</b> recipes to your repertoire, Chili Pie with Green Chile and Cheddar Cornbread Crust might be a recipe you should try. This recipe serves 8 and costs $1.57 per serving. One serving contains <b>644 calories</b>, <b>22g of protein</b>, and <b>40g of fat</b>. This recipe is liked by 15 foodies and cooks. If you have garlic, eggs, cornmeal, and a few other ingredients on hand, you can make it. It is brought to you by Foodista. <b>The Super Bowl</b> will be even more special with this recipe. From preparation to the plate, this recipe takes approximately <b>1 hour</b>. Overall, this recipe earns a <b>solid spoonacular score of 61%</b>. Users who liked this recipe also liked <a href="https://spoonacular.com/recipes/skillet-chili-with-jalapeo-cheddar-cornbread-crust-1277531">Skillet Chili with Jalapeño Cheddar Cornbread Crust</a>, <a href="https://spoonacular.com/recipes/skillet-chili-with-jalapeo-cheddar-cornbread-crust-839045">Skillet Chili with Jalapeño Cheddar Cornbread Crust</a>, and <a href="https://spoonacular.com/recipes/cheddar-chili-cornbread-pie-609897">Cheddar Chili Cornbread Pie</a>.',
      cuisines: [Array],
      dishTypes: [],
      diets: [],
      occasions: [Array],
      analyzedInstructions: [Array],
      spoonacularSourceUrl:
        "https://spoonacular.com/chili-pie-with-green-chile-and-cheddar-cornbread-crust-638568",
      usedIngredientCount: 4,
      missedIngredientCount: 16,
      likes: 0,
      missedIngredients: [Array],
      usedIngredients: [Array],
      unusedIngredients: [Array],
    },
    {
      vegetarian: true,
      vegan: false,
      glutenFree: false,
      dairyFree: false,
      veryHealthy: false,
      cheap: false,
      veryPopular: false,
      sustainable: false,
      lowFodmap: false,
      weightWatcherSmartPoints: 10,
      gaps: "no",
      preparationMinutes: -1,
      cookingMinutes: -1,
      aggregateLikes: 1,
      healthScore: 0,
      creditsText: "Foodista.com – The Cooking Encyclopedia Everyone Can Edit",
      license: "CC BY 3.0",
      sourceName: "Foodista",
      pricePerServing: 25.94,
      extendedIngredients: [Array],
      id: 649593,
      title: "Lemon Cupcakes",
      readyInMinutes: 45,
      servings: 12,
      sourceUrl: "http://www.foodista.com/recipe/775MNV6G/lemon-cupcakes",
      image: "https://spoonacular.com/recipeImages/649593-312x231.jpg",
      imageType: "jpg",
      summary: `Lemon Cupcakes might be a good recipe to expand your dessert recipe box. Watching your figure? This lacto ovo vegetarian recipe has <b>224 calories</b>, <b>3g of protein</b>, and <b>11g of fat</b> per serving. For <b>26 cents per serving</b>, this recipe <b>covers 3%</b> of your daily requirements of vitamins and minerals. This recipe serves 12. 1 person were glad they tried this recipe. From preparation to the plate, this recipe takes approximately <b>45 minutes</b>. Not a lot of people really liked this American dish. A mixture of eggs, lemon zest, self-rising flour, and a handful of other ingredients are all it takes to make this recipe so tasty. It is brought to you by Foodista. With a spoonacular <b>score of 12%</b>, this dish is not so amazing. If you like this recipe, take a look at these similar recipes: <a href="https://spoonacular.com/recipes/gluten-free-lemon-lovers-cupcakes-with-lemon-buttercream-frosting-160191">Gluten-Free Lemon Lover's Cupcakes with Lemon Buttercream Frosting</a>, <a href="https://spoonacular.com/recipes/vegan-lemon-cupcakes-with-fresh-berry-filling-and-lemon-buttercream-382915">Vegan Lemon Cupcakes with Fresh Berry Filling and Lemon Buttercream</a>, and <a href="https://spoonacular.com/recipes/lemon-angel-food-cupcakes-with-lemon-curd-and-mascarpone-frosting-602905">Lemon Angel Food Cupcakes with Lemon Curd and Mascarpone Frosting</a>.`,
      cuisines: [Array],
      dishTypes: [Array],
      diets: [Array],
      occasions: [],
      analyzedInstructions: [Array],
      spoonacularSourceUrl: "https://spoonacular.com/lemon-cupcakes-649593",
      usedIngredientCount: 3,
      missedIngredientCount: 1,
      likes: 0,
      missedIngredients: [Array],
      usedIngredients: [Array],
      unusedIngredients: [Array],
    },
    {
      vegetarian: true,
      vegan: false,
      glutenFree: false,
      dairyFree: false,
      veryHealthy: false,
      cheap: false,
      veryPopular: false,
      sustainable: false,
      lowFodmap: false,
      weightWatcherSmartPoints: 11,
      gaps: "no",
      preparationMinutes: -1,
      cookingMinutes: -1,
      aggregateLikes: 22,
      healthScore: 5,
      creditsText: "Foodista.com – The Cooking Encyclopedia Everyone Can Edit",
      license: "CC BY 3.0",
      sourceName: "Foodista",
      pricePerServing: 63.09,
      extendedIngredients: [Array],
      id: 641759,
      title: "Dutch Baby",
      readyInMinutes: 45,
      servings: 4,
      sourceUrl: "http://www.foodista.com/recipe/WVMGFLGF/dutch-baby",
      image: "https://spoonacular.com/recipeImages/641759-312x231.jpg",
      imageType: "jpg",
      summary: `Dutch Baby could be just the <b>lacto ovo vegetarian</b> recipe you've been looking for. For <b>63 cents per serving</b>, this recipe <b>covers 12%</b> of your daily requirements of vitamins and minerals. This side dish has <b>310 calories</b>, <b>10g of protein</b>, and <b>11g of fat</b> per serving. This recipe serves 4. From preparation to the plate, this recipe takes approximately <b>45 minutes</b>. 22 people have tried and liked this recipe. This recipe from Foodista requires eggs, flour, butter, and milk. Taking all factors into account, this recipe <b>earns a spoonacular score of 46%</b>, which is solid. If you like this recipe, take a look at these similar recipes: <a href="https://spoonacular.com/recipes/going-dutch-apple-spice-buttermilk-dutch-baby-864590">Going Dutch: Apple-Spice Buttermilk Dutch Baby</a>, <a href="https://spoonacular.com/recipes/dutch-baby-141619">Dutch Baby</a>, and <a href="https://spoonacular.com/recipes/dutch-baby-1220881">Dutch Baby</a>.`,
      cuisines: [],
      dishTypes: [Array],
      diets: [Array],
      occasions: [],
      analyzedInstructions: [Array],
      spoonacularSourceUrl: "https://spoonacular.com/dutch-baby-641759",
      usedIngredientCount: 3,
      missedIngredientCount: 1,
      likes: 0,
      missedIngredients: [Array],
      usedIngredients: [Array],
      unusedIngredients: [Array],
    },
    {
      vegetarian: true,
      vegan: false,
      glutenFree: false,
      dairyFree: false,
      veryHealthy: false,
      cheap: false,
      veryPopular: false,
      sustainable: false,
      lowFodmap: false,
      weightWatcherSmartPoints: 10,
      gaps: "no",
      preparationMinutes: -1,
      cookingMinutes: -1,
      aggregateLikes: 109,
      healthScore: 1,
      creditsText: "Full Belly Sisters",
      license: "CC BY-SA 3.0",
      sourceName: "Full Belly Sisters",
      pricePerServing: 54.39,
      extendedIngredients: [Array],
      id: 716407,
      title: "Simple Whole Wheat Crepes",
      readyInMinutes: 45,
      servings: 4,
      sourceUrl:
        "http://fullbellysisters.blogspot.com/2014/11/simple-whole-wheat-crepes.html",
      image: "https://spoonacular.com/recipeImages/716407-312x231.jpg",
      imageType: "jpg",
      summary: `Simple Whole Wheat Crepes might be just the breakfast you are searching for. This recipe makes 4 servings with <b>272 calories</b>, <b>10g of protein</b>, and <b>14g of fat</b> each. For <b>54 cents per serving</b>, this recipe <b>covers 7%</b> of your daily requirements of vitamins and minerals. It is a good option if you're following a <b>lacto ovo vegetarian</b> diet. It is brought to you by fullbellysisters.blogspot.com. 109 people have tried and liked this recipe. If you have milk, eggs, flour, and a few other ingredients on hand, you can make it. This recipe is typical of Mediterranean cuisine. From preparation to the plate, this recipe takes about <b>45 minutes</b>. All things considered, we decided this recipe <b>deserves a spoonacular score of 32%</b>. This score is not so great. <a href="https://spoonacular.com/recipes/whole-wheat-crepes-882970">Whole Wheat Crepes</a>, <a href="https://spoonacular.com/recipes/whole-wheat-crpes-665280">Whole Wheat Crêpes</a>, and <a href="https://spoonacular.com/recipes/whole-wheat-crpes-520226">Whole Wheat Crêpes</a> are very similar to this recipe.`,
      cuisines: [Array],
      dishTypes: [Array],
      diets: [Array],
      occasions: [],
      analyzedInstructions: [Array],
      spoonacularSourceUrl:
        "https://spoonacular.com/simple-whole-wheat-crepes-716407",
      usedIngredientCount: 3,
      missedIngredientCount: 1,
      likes: 0,
      missedIngredients: [Array],
      usedIngredients: [Array],
      unusedIngredients: [Array],
    },
  ],
  offset: 0,
  number: 10,
  totalResults: 3198,
};
